sudo: false
os: linux

language: node_js
node_js:
  - "node"

install:
  - npm install standard -g
  - npm install htmlhint -g

script: 
  - standard --fix
  - htmlhint --config .htmlhintrc *.{htm,html}
